apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: we94tc5my-python 
  janus-idp.io/tekton: we94tc5my-python
  backstage.io/kubernetes-id: we94tc5my-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: we94tc5my-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  